language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm i
script:
  - npm run test && npm run coverage
